// campos obrigatorios:
// models: size, quantity, salePrice, model_id, category, buyPrice, egiste..de
// product: code, brand, title, brand_id, register_brand_date, category

export const ADD_PRODUCT = [{
  code: "123456789",
  brand: "Fornecedor Teste",
  title: "Sem mundial",
  brand_id: "19841732408150169",
  status: 'active',
  description:
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque delectus ducimus, atque eos amet, nesciunt, expedita sit adipisci ex totam numquam quibusdam magni. Saepe dolorem iste tenetur optio repudiandae officiis.",
  register_brand_date: "Sat Nov 23 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
  category: "Roupas Femininas",
  models: [
    {
      size: "ÚNICO",
      quantity: 22,
      salePrice: 112.34,
      buyPrice: 123.45,
      color: "AZUL",
      model_id: "1732407838659",
      status: 'active',
      imgItem: "600/800",
      material: "Algodão",
      style: "Casual",
      register_date: "Sat Nov 23 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
      category: "Roupas Femininas",
      customAttributes: {
        gender: "Feminino",
        season: "Verão",
      }
    },
    {
      size: "G",
      quantity: 33,
      salePrice: 234.34,
      buyPrice: 345.67,
      color: "Rosa",
      model_id: "1732408091017",
      status: 'active',
      imgItem: "600/800",
      material: "Algodão",
      style: "Casual",
      register_date: "Sat Nov 23 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
      category: "Roupas Femininas",
      customAttributes: {
        gender: "Feminino",
        season: "Inverno",
      },
    },
  ],
}, {
    code: "987654321",
    brand: "Fornecedor Exemplo",
    title: "Produto Exemplo",
    brand_id: "19841732408150170",
    status: 'active',
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque delectus ducimus, atque eos amet, nesciunt, expedita sit adipisci ex totam numquam quibusdam magni. Saepe dolorem iste tenetur optio repudiandae officiis.",
    register_brand_date: "Sun Nov 24 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Calçados",
    models: [
      {
        size: "42",
        quantity: 15,
        salePrice: 150.00,
        buyPrice: 100.00,
        color: "Preto",
        model_id: "1732407838660",
        status: 'active',
        imgItem: "600/800",
        material: "Couro",
        style: "Formal",
        register_date: "Sun Nov 24 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Calçados",
        customAttributes: {
          gender: "Masculino",
          season: "Inverno",
        }
      },
      {
        size: "43",
        quantity: 10,
        salePrice: 160.00,
        buyPrice: 110.00,
        color: "Marrom",
        model_id: "1732408091018",
        status: 'active',
        imgItem: "600/800",
        material: "Couro",
        style: "Formal",
        register_date: "Sun Nov 24 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Calçados",
        customAttributes: {
          gender: "Masculino",
          season: "Inverno",
        },
      },
    ],
  },
  {
    code: "1122334455",
    brand: "Fornecedor ABC",
    title: "Produto ABC",
    brand_id: "19841732408150171",
    status: 'active',
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque delectus ducimus, atque eos amet, nesciunt, expedita sit adipisci ex totam numquam quibusdam magni. Saepe dolorem iste tenetur optio repudiandae officiis.",
    register_brand_date: "Mon Nov 25 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Acessórios",
    models: [
      {
        size: "M",
        quantity: 50,
        salePrice: 50.00,
        buyPrice: 30.00,
        color: "Vermelho",
        model_id: "1732407838661",
        status: 'active',
        imgItem: "600/800",
        material: "Plástico",
        style: "Esportivo",
        register_date: "Mon Nov 25 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Acessórios",
        customAttributes: {
          gender: "Unissex",
          season: "Verão",
        }
      },
    ],
  },
  {
    code: "5566778899",
    brand: "Fornecedor XYZ",
    title: "Produto XYZ",
    brand_id: "19841732408150172",
    status: 'active',
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque delectus ducimus, atque eos amet, nesciunt, expedita sit adipisci ex totam numquam quibusdam magni. Saepe dolorem iste tenetur optio repudiandae officiis.",
    register_brand_date: "Tue Nov 26 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Eletrônicos",
    models: [
      {
        size: "ÚNICO",
        quantity: 100,
        salePrice: 500.00,
        buyPrice: 400.00,
        color: "Preto",
        model_id: "1732407838662",
        status: 'active',
        imgItem: "600/800",
        material: "Metal",
        style: "Moderno",
        register_date: "Tue Nov 26 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Eletrônicos",
        customAttributes: {
          warranty: "2 anos",
          voltage: "220V",
        }
      },
    ],
  },
  {
    code: "9988776655",
    brand: "Fornecedor DEF",
    title: "Produto DEF",
    brand_id: "19841732408150173",
    status: 'active',
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque delectus ducimus, atque eos amet, nesciunt, expedita sit adipisci ex totam numquam quibusdam magni. Saepe dolorem iste tenetur optio repudiandae officiis.",
    register_brand_date: "Wed Nov 27 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Roupas Masculinas",
    models: [
      {
        size: "P",
        quantity: 20,
        salePrice: 80.00,
        buyPrice: 60.00,
        color: "Azul",
        model_id: "1732407838663",
        status: 'active',
        imgItem: "600/800",
        material: "Algodão",
        style: "Casual",
        register_date: "Wed Nov 27 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Roupas Masculinas",
        customAttributes: {
          gender: "Masculino",
          season: "Verão",
        }
      },
      {
        size: "M",
        quantity: 25,
        salePrice: 90.00,
        buyPrice: 70.00,
        color: "Verde",
        model_id: "1732408091019",
        status: 'active',
        imgItem: "600/800",
        material: "Algodão",
        style: "Casual",
        register_date: "Wed Nov 27 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Roupas Masculinas",
        customAttributes: {
          gender: "Masculino",
          season: "Verão",
        },
      },
    ],
  },
  {
    code: "1122446688",
    brand: "Fornecedor GHI",
    title: "Produto GHI",
    brand_id: "19841732408150174",
    status: 'active',
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque delectus ducimus, atque eos amet, nesciunt, expedita sit adipisci ex totam numquam quibusdam magni. Saepe dolorem iste tenetur optio repudiandae officiis.",
    register_brand_date: "Thu Nov 28 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Calçados",
    models: [
      {
        size: "39",
        quantity: 30,
        salePrice: 120.00,
        buyPrice: 90.00,
        color: "Branco",
        model_id: "1732407838664",
        status: 'active',
        imgItem: "600/800",
        material: "Couro",
        style: "Esportivo",
        register_date: "Thu Nov 28 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Calçados",
        customAttributes: {
          gender: "Unissex",
          season: "Verão",
        }
      },
      {
        size: "40",
        quantity: 25,
        salePrice: 130.00,
        buyPrice: 100.00,
        color: "Preto",
        model_id: "1732408091020",
        status: 'active',
        imgItem: "600/800",
        material: "Couro",
        style: "Esportivo",
        register_date: "Thu Nov 28 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Calçados",
        customAttributes: {
          gender: "Unissex",
          season: "Verão",
        },
      },
    ],
  },
  {
    code: "2233445566",
    brand: "Fornecedor JKL",
    title: "Produto JKL",
    brand_id: "19841732408150175",
    status: 'active',
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque delectus ducimus, atque eos amet, nesciunt, expedita sit adipisci ex totam numquam quibusdam magni. Saepe dolorem iste tenetur optio repudiandae officiis.",
    register_brand_date: "Fri Nov 29 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Acessórios",
    models: [
      {
        size: "ÚNICO",
        quantity: 40,
        salePrice: 60.00,
        buyPrice: 40.00,
        color: "Amarelo",
        model_id: "1732407838665",
        status: 'active',
        imgItem: "600/800",
        material: "Plástico",
        style: "Casual",
        register_date: "Fri Nov 29 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Acessórios",
        customAttributes: {
          gender: "Unissex",
          season: "Primavera",
        }
      },
    ],
  },
  {
    code: "3344556677",
    brand: "Fornecedor MNO",
    title: "Produto MNO",
    brand_id: "19841732408150176",
    status: 'active',
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque delectus ducimus, atque eos amet, nesciunt, expedita sit adipisci ex totam numquam quibusdam magni. Saepe dolorem iste tenetur optio repudiandae officiis.",
    register_brand_date: "Sat Nov 30 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Eletrônicos",
    models: [
      {
        size: "ÚNICO",
        quantity: 80,
        salePrice: 700.00,
        buyPrice: 600.00,
        color: "Cinza",
        model_id: "1732407838666",
        status: 'active',
        imgItem: "600/800",
        material: "Metal",
        style: "Moderno",
        register_date: "Sat Nov 30 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Eletrônicos",
        customAttributes: {
          warranty: "1 ano",
          voltage: "110V",
        }
      },
    ],
  },
  {
    code: "4455667788",
    brand: "Fornecedor PQR",
    title: "Produto PQR",
    brand_id: "19841732408150177",
    status: 'active',
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque delectus ducimus, atque eos amet, nesciunt, expedita sit adipisci ex totam numquam quibusdam magni. Saepe dolorem iste tenetur optio repudiandae officiis.",
    register_brand_date: "Sun Dec 01 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Roupas Femininas",
    models: [
      {
        size: "M",
        quantity: 35,
        salePrice: 100.00,
        buyPrice: 80.00,
        color: "Roxo",
        model_id: "1732407838667",
        status: 'active',
        imgItem: "600/800",
        material: "Algodão",
        style: "Casual",
        register_date: "Sun Dec 01 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Roupas Femininas",
        customAttributes: {
          gender: "Feminino",
          season: "Outono",
        }
      },
      {
        size: "G",
        quantity: 40,
        salePrice: 110.00,
        buyPrice: 90.00,
        color: "Roxo",
        model_id: "1732408091021",
        status: 'active',
        imgItem: "600/800",
        material: "Algodão",
        style: "Casual",
        register_date: "Sun Dec 01 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Roupas Femininas",
        customAttributes: {
          gender: "Feminino",
          season: "Outono",
        },
      },
    ],
  },
  {
    code: "5566778899",
    brand: "Fornecedor STU",
    title: "Produto STU",
    brand_id: "19841732408150178",
    status: 'active',
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque delectus ducimus, atque eos amet, nesciunt, expedita sit adipisci ex totam numquam quibusdam magni. Saepe dolorem iste tenetur optio repudiandae officiis.",
    register_brand_date: "Mon Dec 02 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Calçados",
    models: [
      {
        size: "41",
        quantity: 20,
        salePrice: 140.00,
        buyPrice: 110.00,
        color: "Azul",
        model_id: "1732407838668",
        status: 'active',
        imgItem: "600/800",
        material: "Couro",
        style: "Formal",
        register_date: "Mon Dec 02 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Calçados",
        customAttributes: {
          gender: "Masculino",
          season: "Primavera",
        }
      },
    ],
  },
  {
    code: "6677889900",
    brand: "Fornecedor VWX",
    title: "Produto VWX",
    brand_id: "19841732408150179",
    status: 'active',
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque delectus ducimus, atque eos amet, nesciunt, expedita sit adipisci ex totam numquam quibusdam magni. Saepe dolorem iste tenetur optio repudiandae officiis.",
    register_brand_date: "Tue Dec 03 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Acessórios",
    models: [
      {
        size: "ÚNICO",
        quantity: 60,
        salePrice: 70.00,
        buyPrice: 50.00,
        color: "Verde",
        model_id: "1732407838669",
        status: 'active',
        imgItem: "600/800",
        material: "Plástico",
        style: "Casual",
        register_date: "Tue Dec 03 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Acessórios",
        customAttributes: {
          gender: "Unissex",
          season: "Verão",
        }
      },
    ],
  },
  {
    code: "7788990011",
    brand: "Fornecedor YZA",
    title: "Produto YZA",
    brand_id: "19841732408150180",
    status: 'active',
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque delectus ducimus, atque eos amet, nesciunt, expedita sit adipisci ex totam numquam quibusdam magni. Saepe dolorem iste tenetur optio repudiandae officiis.",
    register_brand_date: "Wed Dec 04 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Eletrônicos",
    models: [
      {
        size: "ÚNICO",
        quantity: 90,
        salePrice: 800.00,
        buyPrice: 700.00,
        color: "Preto",
        model_id: "1732407838670",
        status: 'active',
        imgItem: "600/800",
        material: "Metal",
        style: "Moderno",
        register_date: "Wed Dec 04 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Eletrônicos",
        customAttributes: {
          warranty: "3 anos",
          voltage: "220V",
        }
      },
    ],
  },
  {
    code: "987654321",
    brand: "Fornecedor B",
    title: "Produto B",
    brand_id: "19841732408150170",
    status: 'active',
    description: "Descrição do produto B.",
    register_brand_date: "Sun Nov 24 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Calçados",
    models: [
      {
        size: "42",
        quantity: 15,
        salePrice: 150.00,
        buyPrice: 100.00,
        color: "Preto",
        model_id: "17324078386601",
        status: 'active',
        imgItem: "600/800",
        material: "Couro",
        style: "Formal",
        register_date: "Sun Nov 24 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Calçados Masculinos",
        customAttributes: {
          gender: "Masculino",
          season: "Inverno",
        }
      },
      {
        size: "43",
        quantity: 10,
        salePrice: 160.00,
        buyPrice: 110.00,
        color: "Marrom",
        model_id: "17324080910182",
        status: 'active',
        imgItem: "600/800",
        material: "Couro",
        style: "Formal",
        register_date: "Sun Nov 24 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Calçados Masculinos",
        customAttributes: {
          gender: "Masculino",
          season: "Inverno",
        },
      },
    ],
  },
  {
    code: "1122334455",
    brand: "Fornecedor C",
    title: "Produto C",
    brand_id: "19841732408150171",
    status: 'active',
    description: "Descrição do produto C.",
    register_brand_date: "Mon Nov 25 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Acessórios",
    models: [
      {
        size: "M",
        quantity: 50,
        salePrice: 50.00,
        buyPrice: 30.00,
        color: "Vermelho",
        model_id: "17324078386611",
        status: 'active',
        imgItem: "600/800",
        material: "Plástico",
        style: "Esportivo",
        register_date: "Mon Nov 25 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Acessórios Esportivos",
        customAttributes: {
          gender: "Unissex",
          season: "Verão",
        }
      },
      {
        size: "L",
        quantity: 40,
        salePrice: 55.00,
        buyPrice: 35.00,
        color: "Azul",
        model_id: "173240809101912",
        status: 'active',
        imgItem: "600/800",
        material: "Plástico",
        style: "Esportivo",
        register_date: "Mon Nov 25 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Acessórios Esportivos",
        customAttributes: {
          gender: "Unissex",
          season: "Verão",
        },
      },
    ],
  },
  {
    code: "2233445566",
    brand: "Fornecedor D",
    title: "Produto D",
    brand_id: "19841732408150172",
    status: 'active',
    description: "Descrição do produto D.",
    register_brand_date: "Tue Nov 26 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Eletrônicos",
    models: [
      {
        size: "ÚNICO",
        quantity: 30,
        salePrice: 200.00,
        buyPrice: 150.00,
        color: "Preto",
        model_id: "17324078386621",
        status: 'active',
        imgItem: "600/800",
        material: "Metal",
        style: "Moderno",
        register_date: "Tue Nov 26 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Eletrônicos",
        customAttributes: {
          warranty: "1 ano",
          voltage: "220V",
        }
      },
      {
        size: "ÚNICO",
        quantity: 20,
        salePrice: 250.00,
        buyPrice: 180.00,
        color: "Branco",
        model_id: "1732408091021230",
        status: 'active',
        imgItem: "600/800",
        material: "Metal",
        style: "Moderno",
        register_date: "Tue Nov 26 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Eletrônicos",
        customAttributes: {
          warranty: "2 anos",
          voltage: "110V",
        },
      },
    ],
  },
  {
    code: "3344556677",
    brand: "Fornecedor E",
    title: "Produto E",
    brand_id: "19841732408150173",
    status: 'active',
    description: "Descrição do produto E.",
    register_brand_date: "Wed Nov 27 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Móveis",
    models: [
      {
        size: "Grande",
        quantity: 10,
        salePrice: 500.00,
        buyPrice: 400.00,
        color: "Marrom",
        model_id: "173240783866113",
        status: 'active',
        imgItem: "600/800",
        material: "Madeira",
        style: "Rústico",
        register_date: "Wed Nov 27 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Móveis de Sala",
        customAttributes: {
          weight: "50kg",
          dimensions: "200x100x50cm",
        }
      },
      {
        size: "Médio",
        quantity: 15,
        salePrice: 450.00,
        buyPrice: 350.00,
        color: "Bege",
        model_id: "1732408091012321",
        status: 'active',
        imgItem: "600/800",
        material: "Madeira",
        style: "Rústico",
        register_date: "Wed Nov 27 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Móveis de Sala",
        customAttributes: {
          weight: "40kg",
          dimensions: "180x90x45cm",
        },
      },
    ],
  },
  {
    code: "4455667788",
    brand: "Fornecedor F",
    title: "Produto F",
    brand_id: "19841732408150174",
    status: 'active',
    description: "Descrição do produto F.",
    register_brand_date: "Thu Nov 28 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Brinquedos",
    models: [
      {
        size: "Pequeno",
        quantity: 100,
        salePrice: 30.00,
        buyPrice: 20.00,
        color: "Amarelo",
        model_id: "1732407838661234",
        status: 'active',
        imgItem: "600/800",
        material: "Plástico",
        style: "Infantil",
        register_date: "Thu Nov 28 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Brinquedos Educativos",
        customAttributes: {
          ageGroup: "3-5 anos",
          safetyStandards: "EN71",
        }
      },
      {
        size: "Médio",
        quantity: 80,
        salePrice: 40.00,
        buyPrice: 25.00,
        color: "Verde",
        model_id: "1732408091022",
        status: 'active',
        imgItem: "600/800",
        material: "Plástico",
        style: "Infantil",
        register_date: "Thu Nov 28 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Brinquedos Educativos",
        customAttributes: {
          ageGroup: "6-8 anos",
          safetyStandards: "EN71",
        },
      },
    ],
  },
  {
    code: "5566778899",
    brand: "Fornecedor G",
    title: "Produto G",
    brand_id: "19841732408150175",
    status: 'active',
    description: "Descrição do produto G.",
    register_brand_date: "Fri Nov 29 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Ferramentas",
    models: [
      {
        size: "ÚNICO",
        quantity: 50,
        salePrice: 100.00,
        buyPrice: 70.00,
        color: "Cinza",
        model_id: "173240783866125",
        status: 'active',
        imgItem: "600/800",
        material: "Aço",
        style: "Industrial",
        register_date: "Fri Nov 29 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Ferramentas Manuais",
        customAttributes: {
          weight: "2kg",
          dimensions: "30x10x5cm",
        }
      },
      {
        size: "ÚNICO",
        quantity: 40,
        salePrice: 120.00,
        buyPrice: 80.00,
        color: "Preto",
        model_id: "1732408091023",
        status: 'active',
        imgItem: "600/800",
        material: "Aço",
        style: "Industrial",
        register_date: "Fri Nov 29 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Ferramentas Manuais",
        customAttributes: {
          weight: "2.5kg",
          dimensions: "35x12x6cm",
        },
      },
    ],
  },
  {
    code: "6677889900",
    brand: "Fornecedor H",
    title: "Produto H",
    brand_id: "19841732408150176",
    status: 'active',
    description: "Descrição do produto H.",
    register_brand_date: "Sat Nov 30 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Cosméticos",
    models: [
      {
        size: "50ml",
        quantity: 200,
        salePrice: 80.00,
        buyPrice: 50.00,
        color: "Transparente",
        model_id: "1732407838661236",
        status: 'active',
        imgItem: "600/800",
        material: "Vidro",
        style: "Luxo",
        register_date: "Sat Nov 30 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Perfumes",
        customAttributes: {
          fragrance: "Floral",
          duration: "8 horas",
        }
      },
      {
        size: "100ml",
        quantity: 150,
        salePrice: 120.00,
        buyPrice: 70.00,
        color: "Transparente",
        model_id: "1732408091024",
        status: 'active',
        imgItem: "600/800",
        material: "Vidro",
        style: "Luxo",
        register_date: "Sat Nov 30 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Perfumes",
        customAttributes: {
          fragrance: "Amadeirado",
          duration: "12 horas",
        },
      },
    ],
  },
  {
    code: "7788990011",
    brand: "Fornecedor I",
    title: "Produto I",
    brand_id: "19841732408150177",
    status: 'active',
    description: "Descrição do produto I.",
    register_brand_date: "Sun Dec 01 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Livros",
    models: [
      {
        size: "ÚNICO",
        quantity: 300,
        salePrice: 40.00,
        buyPrice: 25.00,
        color: "Colorido",
        model_id: "1732407838123667",
        status: 'active',
        imgItem: "600/800",
        material: "Papel",
        style: "Literatura",
        register_date: "Sun Dec 01 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Livros de Ficção",
        customAttributes: {
          author: "Autor A",
          pages: "300",
        }
      },
      {
        size: "ÚNICO",
        quantity: 250,
        salePrice: 45.00,
        buyPrice: 30.00,
        color: "Colorido",
        model_id: "1732408091025",
        status: 'active',
        imgItem: "600/800",
        material: "Papel",
        style: "Literatura",
        register_date: "Sun Dec 01 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Livros de Ficção",
        customAttributes: {
          author: "Autor B",
          pages: "350",
        },
      },
    ],
  },
  {
    code: "8899001122",
    brand: "Fornecedor J",
    title: "Produto J",
    brand_id: "19841732408150178",
    status: 'active',
    description: "Descrição do produto J.",
    register_brand_date: "Mon Dec 02 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
    category: "Alimentos",
    models: [
      {
        size: "500g",
        quantity: 500,
        salePrice: 10.00,
        buyPrice: 5.00,
        color: "Verde",
        model_id: "17324078386682",
        status: 'active',
        imgItem: "600/800",
        material: "Plástico",
        style: "Orgânico",
        register_date: "Mon Dec 02 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Vegetais",
        customAttributes: {
          expirationDate: "Dec 31 2024",
          origin: "Brasil",
        }
      },
      {
        size: "1kg",
        quantity: 400,
        salePrice: 18.00,
        buyPrice: 10.00,
        color: "Verde",
        model_id: "1732408091026",
        status: 'active',
        imgItem: "600/800",
        material: "Plástico",
        style: "Orgânico",
        register_date: "Mon Dec 02 2024 21:23:58 GMT-0300 (Hora padrão de Brasília)",
        category: "Vegetais",
        customAttributes: {
          expirationDate: "Dec 31 2024",
          origin: "Brasil",
        },
      },
    ],
  },
]

